In [ ]:
# Game Statistics:

# GP: Games Played (45 games)
# W/L: Wins/Losses (22-23 record)
# W_PCT: Win Percentage (0.489 or 48.9%)
# MIN: Total Minutes Played (2,175)

# Shooting:

# FGM/FGA: Field Goals Made/Attempted (1,908/4,148)
# FG_PCT: Field Goal Percentage (46%)
# FG3M/FG3A: Three Pointers Made/Attempted (578/1,663)
# FG3_PCT: Three Point Percentage (34.8%)
# FTM/FTA: Free Throws Made/Attempted (839/1,080)
# FT_PCT: Free Throw Percentage (77.7%)

# Rebounds:

# OREB: Offensive Rebounds (551)
# DREB: Defensive Rebounds (1,491)
# REB: Total Rebounds (2,042)

# Other Stats:

# AST: Assists (1,320)
# TOV: Turnovers (729)
# STL: Steals (470)
# BLK: Blocks (237)
# BLKA: Shots Blocked Against (246)
# PF: Personal Fouls Committed (831)
# PFD: Personal Fouls Drawn (897)
# PTS: Total Points (5,233)
# PLUS_MINUS: Point Differential (-119)

In [ ]:
#now I want to combine this to create a bunch of team dataframes with basic stats 
from sqlalchemy import create_engine, text
import pandas as pd

from nba_api.stats.endpoints import leaguedashteamstats

#create our engine for creating sql entries - this wont work right now 
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

#grab dataframe for teams
stats = leaguedashteamstats.LeagueDashTeamStats()
team_df = stats.get_data_frames()[0]
team_df = team_df.set_index('TEAM_ID')

with engine.connect() as conn:
    #start sql transaction
    with conn.begin():
        # Delete recent records of teams if we already added them 
        delete_query = text("""
        DELETE FROM "all_teams_misc_stats" 
        """)
        
        conn.execute(delete_query)
#once we've created the dataframe, we want to push that to a SQL database
#df to sql
#append, fail, repalce for the if_exists parameter
filename = f"all_teams_misc_stats"
team_df.to_sql(filename, engine, if_exists='append', index=True)

print("Basic updated retrieved for all teams!")

Basic updated retrieved for all teams!

In [ ]:
#below this point is iteration that helped create the program above!

In [57]:
from nba_api.stats.endpoints import leaguedashteamstats
import pandas as pd

stats = leaguedashteamstats.LeagueDashTeamStats()
df = stats.get_data_frames()[0]
pd.set_option('display.max_columns', 30)
df

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,...,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,45,22,23,0.489,2175.0,1908,4148,0.460,578,1663,0.348,839,1080,...,3,5,16,6,16,8,4,27,2,9,21,13,3,10,21
1,1610612738,Boston Celtics,46,32,14,0.696,2233.0,1913,4194,0.456,819,2252,0.364,750,949,...,17,21,9,11,3,5,13,1,20,5,5,4,9,4,3
2,1610612751,Brooklyn Nets,46,14,32,0.304,2223.0,1726,3916,0.441,640,1800,0.356,769,967,...,13,14,6,22,27,28,17,24,24,29,26,27,5,24,28
3,1610612766,Charlotte Hornets,42,12,30,0.286,2031.0,1626,3774,0.431,598,1731,0.345,667,861,...,29,30,18,7,28,23,28,18,23,24,18,16,23,30,24
4,1610612741,Chicago Bulls,46,19,27,0.413,2213.0,1970,4231,0.466,728,1966,0.370,688,865,...,28,29,5,24,1,3,3,19,21,18,17,11,30,6,22
5,1610612739,Cleveland Cavaliers,45,36,9,0.800,2160.0,2007,4041,0.497,734,1846,0.398,744,954,...,18,20,15,21,10,16,5,5,11,26,7,11,14,2,2
6,1610612742,Dallas Mavericks,46,24,22,0.522,2213.0,1927,4039,0.477,592,1608,0.368,848,1095,...,2,2,19,14,5,7,18,17,13,4,12,20,4,7,10
7,1610612743,Denver Nuggets,45,28,17,0.622,2180.0,2031,4038,0.503,537,1399,0.384,827,1083,...,5,4,26,12,4,6,1,15,10,16,20,6,5,3,7
8,1610612765,Detroit Pistons,45,23,22,0.511,2180.0,1872,3999,0.468,597,1638,0.364,709,915,...,26,24,17,13,8,9,18,23,25,11,12,25,22,12,18
9,1610612744,Golden State Warriors,45,22,23,0.489,2165.0,1843,4125,0.447,695,1899,0.366,627,875,...,30,27,30,3,12,4,7,14,9,12,29,19,29,16,15
10,1610612745,Houston Rockets,44,30,14,0.682,2127.0,1851,4117,0.450,540,1576,0.343,782,1039,...,10,6,27,1,18,2,29,8,8,13,25,18,7,13,6
11,1610612754,Indiana Pacers,45,25,20,0.556,2170.0,1950,3983,0.490,571,1533,0.372,727,940,...,21,22,20,27,19,26,8,12,12,10,9,17,19,11,13
12,1610612746,LA Clippers,45,26,19,0.578,2170.0,1818,3881,0.468,550,1535,0.358,762,960,...,15,17,8,19,9,13,23,26,3,23,9,14,25,20,8
13,1610612747,Los Angeles Lakers,43,25,18,0.581,2069.0,1752,3685,0.475,513,1450,0.354,778,985,...,12,10,11,29,29,29,20,3,27,22,2,1,17,26,19
14,1610612763,Memphis Grizzlies,46,31,15,0.674,2208.0,2086,4287,0.487,656,1756,0.374,860,1114,...,1,1,22,2,2,1,2,29,6,3,26,30,2,1,4
15,1610612748,Miami Heat,44,22,22,0.500,2137.0,1742,3825,0.455,624,1700,0.367,761,957,...,16,19,7,26,11,24,16,7,14,30,16,3,27,23,14
16,1610612749,Milwaukee Bucks,43,25,18,0.581,2069.0,1795,3721,0.482,614,1578,0.389,712,964,...,24,16,29,30,6,25,25,6,29,15,1,8,23,21,9
17,1610612750,Minnesota Timberwolves,45,24,21,0.533,2170.0,1782,3860,0.462,681,1773,0.384,732,933,...,20,23,13,18,14,17,21,20,17,16,11,9,16,17,11
18,1610612740,New Orleans Pelicans,46,12,34,0.261,2218.0,1841,4151,0.444,563,1636,0.344,779,1017,...,11,8,24,5,26,15,15,16,4,7,22,15,20,13,29
19,1610612752,New York Knicks,46,30,16,0.652,2218.0,2001,4052,0.494,605,1602,0.378,785,971,...,9,13,3,15,13,11,9,8,18,28,15,5,8,5,5
20,1610612760,Oklahoma City Thunder,45,37,8,0.822,2160.0,1954,4127,0.473,618,1728,0.358,720,872,...,23,28,1,23,15,20,14,1,1,7,14,26,21,9,1
21,1610612753,Orlando Magic,47,24,23,0.511,2256.0,1759,4009,0.439,526,1722,0.305,833,1088,...,4,3,25,10,23,21,24,22,5,2,8,28,1,22,16
22,1610612755,Philadelphia 76ers,44,17,27,0.386,2132.0,1700,3775,0.450,556,1608,0.346,800,1021,...,6,7,14,25,30,30,30,11,7,27,19,21,9,28,23
23,1610612756,Phoenix Suns,44,23,21,0.523,2122.0,1780,3755,0.474,608,1624,0.374,792,991,...,8,9,4,28,19,27,12,8,25,18,3,7,13,18,17
24,1610612757,Portland Trail Blazers,46,17,29,0.370,2208.0,1827,4081,0.448,563,1658,0.340,741,967,...,19,14,23,4,24,12,27,28,14,5,28,23,9,19,27
25,1610612758,Sacramento Kings,45,23,22,0.511,2185.0,1949,4108,0.474,568,1622,0.350,800,984,...,6,11,2,16,7,10,11,4,16,21,6,21,15,8,12
26,1610612759,San Antonio Spurs,43,20,23,0.465,2074.0,1750,3821,0.458,593,1706,0.348,722,914,...,22,25,10,17,17,18,10,13,28,1,4,2,28,25,20
27,1610612761,Toronto Raptors,45,13,32,0.289,2175.0,1892,4021,0.471,514,1467,0.350,711,958,...,25,18,28,8,22,14,6,25,19,24,24,29,17,15,25
28,1610612762,Utah Jazz,43,10,33,0.233,2074.0,1711,3753,0.456,595,1675,0.355,769,976,...,13,12,12,9,24,19,25,30,30,18,30,10,12,27,26
29,1610612764,Washington Wizards,44,6,38,0.136,2117.0,1745,3988,0.438,561,1686,0.333,691,894,...,27,26,21,20,21,22,22,21,22,13,22,24,26,29,30

In [59]:
# Or use TEAM_ID as the index
df = df.set_index('TEAM_ID')
# # Check the data type first
# print(df['TEAM_ID'].dtype)
# df = df.reset_index()
# print(df.columns.tolist())
print(df.loc[1610612737])

team_df = df.loc[[1610612737]]
pd.set_option('display.max_columns', 45)
team_df

TEAM_NAME          Atlanta Hawks
GP                            45
W                             22
L                             23
W_PCT                      0.489
MIN                       2175.0
FGM                         1908
FGA                         4148
FG_PCT                      0.46
FG3M                         578
FG3A                        1663
FG3_PCT                    0.348
FTM                          839
FTA                         1080
FT_PCT                     0.777
OREB                         551
DREB                        1491
REB                         2042
AST                         1320
TOV                        729.0
STL                          470
BLK                          237
BLKA                         246
PF                           831
PFD                          897
PTS                         5233
PLUS_MINUS                -119.0
GP_RANK                       10
W_RANK                        18
L_RANK                        18
W_PCT_RANK                    19
MIN_RANK                      13
FGM_RANK                      11
FGA_RANK                       5
FG_PCT_RANK                   17
FG3M_RANK                     18
FG3A_RANK                     15
FG3_PCT_RANK                  23
FTM_RANK                       3
FTA_RANK                       5
FT_PCT_RANK                   16
OREB_RANK                      6
DREB_RANK                     16
REB_RANK                       8
AST_RANK                       4
TOV_RANK                      27
STL_RANK                       2
BLK_RANK                       9
BLKA_RANK                     21
PF_RANK                       13
PFD_RANK                       3
PTS_RANK                      10
PLUS_MINUS_RANK               21
Name: 1610612737, dtype: object

,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,...,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
TEAM_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1610612737,Atlanta Hawks,45,22,23,0.489,2175.0,1908,4148,0.46,578,1663,0.348,839,1080,0.777,551,1491,2042,1320,729.0,470,237,...,13,11,5,17,18,15,23,3,5,16,6,16,8,4,27,2,9,21,13,3,10,21

In [62]:
# Game Statistics:

# GP: Games Played (45 games)
# W/L: Wins/Losses (22-23 record)
# W_PCT: Win Percentage (0.489 or 48.9%)
# MIN: Total Minutes Played (2,175)

# Shooting:

# FGM/FGA: Field Goals Made/Attempted (1,908/4,148)
# FG_PCT: Field Goal Percentage (46%)
# FG3M/FG3A: Three Pointers Made/Attempted (578/1,663)
# FG3_PCT: Three Point Percentage (34.8%)
# FTM/FTA: Free Throws Made/Attempted (839/1,080)
# FT_PCT: Free Throw Percentage (77.7%)

# Rebounds:

# OREB: Offensive Rebounds (551)
# DREB: Defensive Rebounds (1,491)
# REB: Total Rebounds (2,042)

# Other Stats:

# AST: Assists (1,320)
# TOV: Turnovers (729)
# STL: Steals (470)
# BLK: Blocks (237)
# BLKA: Shots Blocked Against (246)
# PF: Personal Fouls Committed (831)
# PFD: Personal Fouls Drawn (897)
# PTS: Total Points (5,233)
# PLUS_MINUS: Point Differential (-119)

In [ ]:
#now I want to combine this to create a bunch of team dataframes with basic stats 
from sqlalchemy import create_engine
from requests.exceptions import ReadTimeout
import random
import time 

from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguedashteamstats
import pandas as pd

#create our engine for creating sql entries - this wont work right now 
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

#create our list of teams
nba_teams = teams.get_teams()
#grab dataframe for teams
stats = leaguedashteamstats.LeagueDashTeamStats()
df = stats.get_data_frames()[0]
df = df.set_index('TEAM_ID')

#iterate through all nba teams
for team in nba_teams:
    try:
        print(f"getting stats for {team['full_name']}")
    
        #set team_id
        team_id = team['id']
        #create dataframe for each team 
        team_misc = df.loc[[team_id]]
    
        #this will help create our dataframes at the end of each loop
        print(f"DataFrame created for {team['full_name']}")
    
        #once we've created the dataframe, we want to push that to a SQL database
        #df to sql
        #append, fail, repalce for the if_exists parameter
        filename = f"{team['full_name'].replace(' ', '_')}_misc_stats"
        team_misc.to_sql(filename, engine, if_exists='replace', index=False)
        print()
        time.sleep(round(random.uniform(1, 2), 1))
        
    except (ReadTimeout, json.decoder.JSONDecodeError) as e:
        print(f"Error for {team['full_name']}: {e} - retrying after 60 seconds")
        time.sleep(60)
        continue

print("Basic stats retrieved for all teams!")

getting stats for Atlanta Hawks
DataFrame created for Atlanta Hawks

getting stats for Boston Celtics
DataFrame created for Boston Celtics

getting stats for Cleveland Cavaliers
DataFrame created for Cleveland Cavaliers

getting stats for New Orleans Pelicans
DataFrame created for New Orleans Pelicans

getting stats for Chicago Bulls
DataFrame created for Chicago Bulls

getting stats for Dallas Mavericks
DataFrame created for Dallas Mavericks

getting stats for Denver Nuggets
DataFrame created for Denver Nuggets

getting stats for Golden State Warriors
DataFrame created for Golden State Warriors

getting stats for Houston Rockets
DataFrame created for Houston Rockets

getting stats for Los Angeles Clippers
DataFrame created for Los Angeles Clippers

getting stats for Los Angeles Lakers
DataFrame created for Los Angeles Lakers

getting stats for Miami Heat
DataFrame created for Miami Heat

getting stats for Milwaukee Bucks
DataFrame created for Milwaukee Bucks

getting stats for Minnesota Timberwolves
DataFrame created for Minnesota Timberwolves

getting stats for Brooklyn Nets
DataFrame created for Brooklyn Nets

getting stats for New York Knicks
DataFrame created for New York Knicks

getting stats for Orlando Magic
DataFrame created for Orlando Magic

getting stats for Indiana Pacers
DataFrame created for Indiana Pacers

getting stats for Philadelphia 76ers
DataFrame created for Philadelphia 76ers

getting stats for Phoenix Suns
DataFrame created for Phoenix Suns

getting stats for Portland Trail Blazers
DataFrame created for Portland Trail Blazers

getting stats for Sacramento Kings
DataFrame created for Sacramento Kings

getting stats for San Antonio Spurs
DataFrame created for San Antonio Spurs

getting stats for Oklahoma City Thunder
DataFrame created for Oklahoma City Thunder

getting stats for Toronto Raptors
DataFrame created for Toronto Raptors

getting stats for Utah Jazz
DataFrame created for Utah Jazz

getting stats for Memphis Grizzlies
DataFrame created for Memphis Grizzlies

getting stats for Washington Wizards
DataFrame created for Washington Wizards

getting stats for Detroit Pistons
DataFrame created for Detroit Pistons

getting stats for Charlotte Hornets
DataFrame created for Charlotte Hornets